# Generated by Django 4.2 on 2023-05-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="users_id",
            new_name="user",
        ),
    ]
